force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo.</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Jogador__c/fields/DataMorte__c.field-meta.xml
<CustomField>
    <fullName>DataMorte__c</fullName>
    <description>Usado para a data da morte.</description>
    <inlineHelpText>Data da Morte do jagdor.</inlineHelpText>
    <label>Data da Morte</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jagador foi eliminado.</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AssassinatosTriggerHandler.cls
public with sharing class AssassinatosTriggerHandler {
    

    public static void afterInsert(List<Assassinato__c> records) {
        System.debug('Trigger afterupdate Assassinatos');
        List<String> idsJoradoresAssassinados = new List<String>();

        for (Assassinato__c assassinato : records) { 
            idsJoradoresAssassinados.add(assassinato.Assassinado__c);
        }

        List<Jogador__c> jogadores = [SELECT Id FROM Jogador__c WHERE Id IN :idsJoradoresAssassinados];

        System.debug('Lista de Jogadores Assassinados >> ' + jogadores);

        for (Jogador__c jogador : jogadores) {
            afterInsert(jogador);
        }      
        update jogadores;

    }

    private static void afterInsert(Jogador__c jogador) {
        // Corrigir somente incluir morte (já tratado na trigger Jogador)
        Utils.setValue(jogador, Jogador__c.DataMorte__c, System.now());
        Utils.setValue(jogador, Jogador__c.Eliminado__c, true);
    }
    

}