force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo.</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Jogador__c/fields/Eliminado__c.field-meta.xml
<CustomField>
    <fullName>Eliminado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Usado para informar se o jagador foi eliminado.</description>
    <inlineHelpText>Jogador eliminado?</inlineHelpText>
    <label>Eliminado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Jogador__c/fields/Forca__c.field-meta.xml
<CustomField>
    <fullName>Forca__c</fullName>
    <label>Força</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jogador__c/fields/Inteligencia__c.field-meta.xml
<CustomField>
    <fullName>Inteligencia__c</fullName>
    <label>Iteligência</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Jogador__c/fields/Round__c.field-meta.xml
<CustomField>
    <fullName>Round__c</fullName>
    <label>Round</label>
    <referenceTo>Round__c</referenceTo>
    <relationshipLabel>Jogadores</relationshipLabel>
    <relationshipName>Jogadores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/JogadoresSelector.cls
public with sharing class JogadoresSelector {

    public static List<Jogador__c> selectJogadoresNaoEliminadosDeUmRound(Id id) {
        return [
            SELECT Id, Name, Forca__c, Inteligencia__c, Velocidade__c 
            FROM Jogador__c
            WHERE (Eliminado__c = false AND Round__r.Id = :id)
        ]; 
    }

    public static List<Jogador__c> selectJogadoresNaoEliminados() {
        return [
            SELECT Id, Name, Forca__c, Inteligencia__c, Velocidade__c 
            FROM Jogador__c
            WHERE Eliminado__c = false
        ]; 
    }


    public static List<Jogador__c> selectJogadoresComIds(List<Id> ids) {
        return [
            SELECT Id, Name, Eliminado__c, Forca__c, Inteligencia__c, Velocidade__c  
            FROM Jogador__c
            WHERE Id = :ids
        ]; 
    }

}